### ISSUE TITLE
SG2 To-Do List

### ISSUE THREAD

**Issue by SilentChaos512** [SilentChaos512/SilentGems#28]
Probably best to collect a list of things to be done here, rather than random notes on my destkop. Feel free to chime in if I missed something, but suggestion for new ideas should go in a new issue!

Things not yet re-implemented in 1.9:

Blocks
- [X] Chaos essence/coal blocks (MiscBlocks)
- [X] Chaos altar
- [X] Gem lamps
- [X] Teleporters

Items
- [X] Armor (Functioning, missing some models)
- [X]  Bows ~~(might be a nightmare in 1.9...)~~ ~~(Partially functioning)~~
- [X] Chaos coal ~~(can't be burned currently)~~
- [X] Pet summoners
- [X] Return home charm
- [ ] Chaos gems/runes (may be replaced by something else?)

New ideas on the list (note these may or may not end up in the mod):
- [X] Shinies bag: an item that stores gems (Gemulation)
- [X]  Shields ~~(not sure how practical that is)~~ (Wasn't that hard, surprisingly)
- [X]  Gem glass blocks
- [X]  Enchantments for boosting magic damage ~~and charge speed~~.
- [X] ~~Fishing rods~~ (Probably not worth the effort)

**Comment by M4thG33k** [comment]
The shinies bag sounds like a great idea! Unless you plan on implementing it soon, do you mind if I take a shot at it?

**Comment by SilentChaos512** [comment]
Not at all, go ahead!

**Comment by M4thG33k** [comment]
Shinies bags will most definitely be in the next release of Gemulation, so consider that one done!

**Comment by TyoAtrosa** [comment]
the new armor is working great, though the enchanted effect looks aweful. love the textures on the properly decorated armor, took me a few trys to figure it out and wasted a lot of gems getting my armor looking sweet with a mix of gems and silver.

**Comment by SilentChaos512** [comment]
I've disabled the enchanted glow on armor for now. I just discovered that issue myself. The armor is still a work-in-progress. Hopefully we can get some custom item models sometime in the near future to make decorating easier.
